CSharp/Assigntment3/Assignment3WebApp/ViewModels/EditDesignViewModel.cs
namespace Assignment3WebApp.ViewModels
{
    public class EditDesignViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        //public string Country { get; set; }
        public List<string> Countries { get; set; }
        public List<string> Gender { get; set; } = new List<string>() { "M", "F" };
        public List<Sports> SportsList { get; set; }
        public List<Friends> FriendList { get; set; }   
    }

    public class Sports
    {
        public string Football { get; set; }
        public string BasketBall { get; set; }
        public string Baseball { get; set; }
        public string Soccer { get; set; }
    }

    public class Friends
    {
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    }

}

CSharp/Assigntment3/Assignment3WebApp/ViewModels/ErrorViewModel.cs
namespace Assignment3WebApp.ViewModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSharp/Assigntment3/Assignment3WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Assignment3WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Assignment3WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSharp/Assigntment3/Assignment3WebApp/Controllers/MyFirstController.cs
using Assignment3WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Assignment3WebApp.Controllers
{
    public class MyFirstController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult EditDesign()
        {
            EditDesignViewModel editDesignViewModel = new EditDesignViewModel();
            return View(editDesignViewModel);
        }
    }
}

CSharp/Assigntment3/Assignment3WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CSharp/Assigntment3/Assignment3WebApp/Views/MyFirst/EditDesign.cshtml
@model Assignment3WebApp.ViewModels.EditDesignViewModel
@{
    ViewData["Title"] = "Edit Design";
}
<h1>Edit Design</h1>
<form asp-action="YourActionMethod" method="post">
    <div id="mainDiv">
        <div id="topDiv">
            <h2>Personal Information</h2>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="StreetAddress" class="control-label"></label>
                <input asp-for="StreetAddress" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
            </div>
        </div>

        <div id="middleLeftDiv" class="form-section">
            <h2>Gender</h2>
            <div>
                @foreach (var item in Model.Gender)
                {
                    <div class="form-check">
                        <input asp-for="Gender" type="radio" value="@item" class="form-check-input" />
                        <label class="form-check-label">@item</label>
                    </div>
                }
            </div>
        </div>

        <div id="rightDiv" class="form-section">
            <h2>Countries</h2>
            <div class="form-group">
                <label asp-for="Countries" class="control-label"></label>
                <select asp-for="Countries" class="form-control" asp-items="@(new SelectList(Model.Countries))">
                    <option value="">Select Country</option>
                </select>
            </div>

            <div class="myDivBuffer">
                <h3>My Favorite Sports</h3>
                @if (Model.SportsList != null && Model.SportsList.Count > 0)
                {
                    foreach (var sport in Model.SportsList)
                    {
                        <div>@sport.Football</div>
                        <div>@sport.BasketBall</div>
                        <div>@sport.Baseball</div>
                        <div>@sport.Soccer</div>
                    }
                }
                else
                {
                    <div>No favorite sports available.</div>
                }
            </div>

            <div class="myDivBuffer">
                <h3>My Friends</h3>
                @if (Model.FriendList != null && Model.FriendList.Count > 0)
                {
                    foreach (var friend in Model.FriendList)
                    {
                        <div>@friend.Firstname @friend.LastName, located in @friend.City, @friend.State</div>
                    }
                }
                else
                {
                    <div>No friends available.</div>
                }
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>

CSharp/Assigntment3/Assignment3WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment3WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment3WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment3WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyFirst" asp-action="EditDesign">Edit Design</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Assignment3WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CSharp/Assigntment3/Assignment3WebApp/Views/View.cshtml
@using Assignment3WebApp.ViewModels
@model EditDesignViewModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<div>
    <h4>EditDesignViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Countries)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Countries)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>